In [11]:
import pandas as pd

In [12]:
weather_df = pd.read_csv('sample-data/weather_data_10_years_preprocessed.csv')

weather_df.head()

,Timestamp,temp,visibility,dew_point,feels_like,pressure,humidity,wind_speed,clouds_all,rain_1h,...,weather_Snow_light rain and snow,weather_Snow_light shower sleet,weather_Snow_light shower snow,weather_Snow_light snow,weather_Snow_sleet,weather_Snow_snow,weather_Thunderstorm_thunderstorm,weather_Thunderstorm_thunderstorm with heavy rain,weather_Thunderstorm_thunderstorm with light rain,weather_Thunderstorm_thunderstorm with rain
0,2014-03-06 00:00:00,9.79,10000.0,7.22,6.76,1001,84,6.70,75,NaN,...,False,False,False,False,False,False,False,False,False,False
1,2014-03-06 01:00:00,9.75,10000.0,7.01,6.56,1000,83,7.20,100,NaN,...,False,False,False,False,False,False,False,False,False,False
2,2014-03-06 02:00:00,9.21,10000.0,6.65,6.36,998,84,5.66,100,NaN,...,False,False,False,False,False,False,False,False,False,False
3,2014-03-06 03:00:00,8.67,10000.0,6.12,6.08,998,84,4.63,100,0.21,...,False,False,False,False,False,False,False,False,False,False
4,2014-03-06 04:00:00,8.00,10000.0,6.14,5.25,997,88,4.63,100,0.30,...,False,False,False,False,False,False,False,False,False,False

In [13]:
parking_df = pd.read_csv('sample-data/organized_parking_data_NEW.csv')

parking_df.head()

,Timestamp,North,West,Rose,Health Sciences,Fraser,Thunderbird,University Lot Blvd
0,2018-09-06 10:00:00,951,1016,476,913,556,939,-1
1,2018-09-06 11:00:00,922,1160,609,972,707,1050,-1
2,2018-09-06 12:00:00,833,1206,659,963,724,1072,-1
3,2018-09-06 13:00:00,851,1168,695,953,719,1094,-1
4,2018-09-06 14:00:00,857,1220,710,963,727,1069,-1

In [14]:
# Merge the two DataFrames on 'Timestamp'
combined_df = pd.merge(parking_df, weather_df, on='Timestamp')

print(combined_df)

                 Timestamp  North  West  Rose  Health Sciences  Fraser  \
0      2018-09-06 10:00:00    951  1016   476              913     556
1      2018-09-06 11:00:00    922  1160   609              972     707
2      2018-09-06 12:00:00    833  1206   659              963     724
3      2018-09-06 13:00:00    851  1168   695              953     719
4      2018-09-06 14:00:00    857  1220   710              963     727
...                    ...    ...   ...   ...              ...     ...
50333  2024-03-05 19:00:00     72   232   154              172     119
50334  2024-03-05 20:00:00     10   146   100               91      70
50335  2024-03-05 21:00:00      0    88    44               62      43
50336  2024-03-05 22:00:00      1    64    20               50      32
50337  2024-03-05 23:00:00      0    41     7               43      19

       Thunderbird  University Lot Blvd   temp  visibility  ...  \
0              939                   -1  14.59     10000.0  ...
1             1050                   -1  14.01     10000.0  ...
2             1072                   -1  14.16     10000.0  ...
3             1094                   -1  13.85     10000.0  ...
4             1069                   -1  13.96     10000.0  ...
...            ...                  ...    ...         ...  ...
50333          217                   64   3.21     10000.0  ...
50334          164                   43   4.18     10000.0  ...
50335          121                   34   4.17     10000.0  ...
50336           76                   20   4.57     10000.0  ...
50337           28                   19   4.68     10000.0  ...

       weather_Snow_light rain and snow  weather_Snow_light shower sleet  \
0                                 False                            False
1                                 False                            False
2                                 False                            False
3                                 False                            False
4                                 False                            False
...                                 ...                              ...
50333                             False                            False
50334                             False                            False
50335                             False                            False
50336                             False                            False
50337                             False                            False

       weather_Snow_light shower snow  weather_Snow_light snow  \
0                               False                    False
1                               False                    False
2                               False                    False
3                               False                    False
4                               False                    False
...                               ...                      ...
50333                           False                    False
50334                           False                    False
50335                           False                    False
50336                           False                    False
50337                           False                    False

       weather_Snow_sleet  weather_Snow_snow  \
0                   False              False
1                   False              False
2                   False              False
3                   False              False
4                   False              False
...                   ...                ...
50333               False              False
50334               False              False
50335               False              False
50336               False              False
50337               False              False

       weather_Thunderstorm_thunderstorm  \
0                                  False
1                                  False
2                                  False
3                                  False
4                                  False
...                                  ...
50333                              False
50334                              False
50335                              False
50336                              False
50337                              False

       weather_Thunderstorm_thunderstorm with heavy rain  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
50333                                              False
50334                                              False
50335                                              False
50336                                              False
50337                                              False

       weather_Thunderstorm_thunderstorm with light rain  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
50333                                              False
50334                                              False
50335                                              False
50336                                              False
50337                                              False

       weather_Thunderstorm_thunderstorm with rain
0                                            False
1                                            False
2                                            False
3                                            False
4                                            False
...                                            ...
50333                                        False
50334                                        False
50335                                        False
50336                                        False
50337                                        False

[50338 rows x 51 columns]

In [15]:
combined_df.to_csv('combined_weather_parking.csv', index=False)